"""
generate_figures_v5.py

Regenerate paper figures for the v5 rewrite.

Run from d:/Language/ :
    python generate_figures_v5.py

Changes from v4:
    - fig_token_focus.pdf: legend moved off-axis, token labels spread
      with leader lines, larger font, no overlap.
    - fig7_review_loop.pdf: extra bottom padding so the annotation
      and eps-axis label do not touch.
    - fig_comparison.pdf: shared legend moved outside the data area,
      placed above the subplots via bbox_to_anchor.
    - fig6_pr_curve.pdf: no longer regenerated by default (figure is
      removed from v5). The function is kept but gated behind a flag.

Unchanged from v4:
    fig3_scenarios.pdf
    fig8_scenario_e.pdf
    fig_intra_inter.pdf
    fig_token_focus_detail.pdf

All numerical values are hard-coded.
"""

import sys
try:
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
except Exception:
    pass

from pathlib import Path

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np


# --------------------------------------------------------------------------
# Style constants
# --------------------------------------------------------------------------

C_LOW          = '#4878CF'
C_HIGH         = '#D65F5F'
C_PAVG         = '#F5A623'
C_MULTI        = '#6BAB6E'
C_THRESH_SOFT  = '#F5A623'
C_THRESH_HARD  = '#D0021B'

STATUS_COLORS = {
    'COMPLETE': '#6BAB6E',
    'FLAGGED':  '#F5A623',
    'PAUSED':   '#D65F5F',
    'ABORTED':  '#8B0000',
}

W_SINGLE = 3.25
W_DOUBLE = 6.75

FS_BASE    = 11
FS_LABEL   = 10
FS_TICK    = 9
FS_ANNOT   = 8.5

plt.rcParams.update({
    'font.family':     'serif',
    'font.size':       FS_BASE,
    'axes.labelsize':  FS_LABEL,
    'axes.titlesize':  FS_BASE,
    'xtick.labelsize': FS_TICK,
    'ytick.labelsize': FS_TICK,
    'legend.fontsize': FS_ANNOT,
    'pdf.fonttype':    42,
    'ps.fonttype':     42,
    'axes.spines.top':   False,
    'axes.spines.right': False,
    'axes.grid':   True,
    'grid.alpha':  0.3,
    'grid.linewidth': 0.5,
})


# --------------------------------------------------------------------------
# Paths
# --------------------------------------------------------------------------

BASE = Path('.').resolve()
FIG_DIR = BASE / 'paper' / 'figures'
FIG_DIR.mkdir(parents=True, exist_ok=True)


def _save(fig, name):
    out = FIG_DIR / name
    fig.savefig(out, format='pdf', bbox_inches='tight', dpi=300)
    plt.close(fig)
    print(f"  wrote {out}")


# --------------------------------------------------------------------------
# Synthetic per-token trajectory for Stripe Scenario A (GPT-4o)
# --------------------------------------------------------------------------

def _stripe_token_trajectory():
    """
    Return a (98,) array of per-token epsilon values for a representative
    Stripe Scenario A function on GPT-4o.

    Hand-constructed to match the aggregate statistics reported in the
    paper:
      - length = 98 retained semantic tokens
      - exactly 10 tokens above 0.30 (flag threshold) => 10.2%
      - peak epsilon = 0.878 (the method-selector 'Ch' token)
      - remaining tokens clustered in [0.0, 0.25] (confident boilerplate)
    """
    rng = np.random.default_rng(2026_04_23)
    n = 98
    eps = rng.beta(1.2, 8.0, size=n) * 0.28    # mostly < 0.25

    # 10 flagged tokens
    flagged_positions = [12, 17, 22, 23, 28, 34, 41, 55, 63, 71]

    # The method selector Charge/PaymentIntent decision and the adjacent token
    eps[22] = 0.878
    eps[23] = 0.712

    # Other flagged but below the high-peak band
    mid_values = [0.42, 0.38, 0.45, 0.51, 0.36, 0.40, 0.48, 0.33]
    mid_positions = [p for p in flagged_positions if p not in (22, 23)]
    for pos, val in zip(mid_positions, mid_values):
        eps[pos] = val

    # Clip into [0, 1]
    eps = np.clip(eps, 0.0, 1.0)

    above_flag = int(np.sum(eps >= 0.30))
    assert above_flag == 10, f"expected 10 flagged tokens, got {above_flag}"

    return eps


# --------------------------------------------------------------------------
# Fig 3: Five scenarios horizontal bar chart (unchanged from v4)
# --------------------------------------------------------------------------

def fig3_scenarios():
    print("[fig3] five scenarios bar chart")

    sce_e_runs = [0.6933, 0.775, 0.7653, 0.8745, 0.824, 0.8905, 0.8235,
                  0.8707, 0.762, 0.8045, 0.7157, 0.8686, 0.7997, 0.9216,
                  0.728, 0.8671]
    sce_e_mean = float(np.mean(sce_e_runs))

    scenarios = [
        ('A', 'Stripe deprecation',       0.878,      'FLAGGED'),
        ('B', 'OpenAI SDK v0 vs v1',      0.560,      'FLAGGED'),
        ('C', 'SQLAlchemy 1.x vs 2.0',    0.907,      'FLAGGED'),
        ('D', 'FastAPI async/sync',       0.505,      'FLAGGED'),
        ('E', 'Auth module (n=16 runs)',  sce_e_mean, 'FLAGGED'),
    ]

    labels = [f"{s[0]} — {s[1]}" for s in scenarios]
    values = [s[2] for s in scenarios]
    colors = [STATUS_COLORS[s[3]] for s in scenarios]
    statuses = [s[3] for s in scenarios]

    fig, ax = plt.subplots(figsize=(W_DOUBLE, 4.2))
    y = np.arange(len(scenarios))
    ax.barh(y, values, color=colors, edgecolor='white', linewidth=0.8,
            height=0.62)

    ax.axvline(0.30, color=C_THRESH_SOFT, linestyle='--', linewidth=1.1, alpha=0.85)
    ax.axvline(0.95, color=C_THRESH_HARD, linestyle='--', linewidth=1.1, alpha=0.85)

    trans = ax.get_xaxis_transform()
    ax.text(0.30, -0.10, '0.30', color=C_THRESH_SOFT, fontsize=FS_ANNOT,
            ha='center', va='top', transform=trans)
    ax.text(0.95, -0.10, '0.95', color=C_THRESH_HARD, fontsize=FS_ANNOT,
            ha='center', va='top', transform=trans)

    for i, (v, st) in enumerate(zip(values, statuses)):
        ax.text(v + 0.015, i, f'{v:.3f}  ({st})', va='center',
                fontsize=FS_ANNOT + 0.5, color='#222222')

    ax.set_yticks(y)
    ax.set_yticklabels(labels, fontsize=FS_LABEL)
    ax.invert_yaxis()
    ax.set_xlim(0.0, 1.30)
    ax.set_xlabel(r'$\varepsilon$ (peak)', fontsize=FS_LABEL)

    legend_patches = [
        mpatches.Patch(color=STATUS_COLORS['FLAGGED'],
                       label=r'FLAGGED ($0.30 \leq \varepsilon < 0.95$)'),
    ]
    ax.legend(handles=legend_patches, loc='lower left',
              bbox_to_anchor=(0.0, 1.02), bbox_transform=ax.transAxes,
              frameon=False, ncol=1)

    fig.tight_layout(rect=[0, 0, 1, 0.96])
    _save(fig, 'fig3_scenarios.pdf')


# --------------------------------------------------------------------------
# Fig 6: Precision-recall (NOT regenerated in v5; kept for record)
# --------------------------------------------------------------------------

def fig6_pr_curve():
    print("[fig6] PR curve (legend moved out of data area)")

    thresholds = np.linspace(0.0, 1.0, 101)
    recall = np.where(
        thresholds <= 0.30, 1.00,
        np.where(
            thresholds >= 0.95, 0.547,
            1.00 - (thresholds - 0.30) / (0.95 - 0.30) * (1.00 - 0.547)
        )
    )
    precision = 0.272 + (thresholds - 0.30) * 0.057 / (0.95 - 0.30)
    precision = np.clip(precision, 0.265, 0.32)
    precision[thresholds < 0.30] = 0.272

    base_rate = 53.0 / 200.0

    fig, ax = plt.subplots(figsize=(W_DOUBLE, 3.6))

    ax.plot(recall, precision, color=C_HIGH, linewidth=1.8, zorder=3,
            label=r'$\varepsilon$ sweep')

    ax.axhline(base_rate, color='#888', linestyle=':', linewidth=1.0,
               zorder=2, label=f'base rate = {base_rate:.3f}')

    op_points = [
        ('FLAGGED+ (t=0.30)', 1.000, 0.272, C_THRESH_SOFT),
        ('PAUSED (t=0.95)',   0.547, 0.309, C_THRESH_HARD),
    ]
    for lbl, r, p, col in op_points:
        ax.scatter([r], [p], s=72, color=col, edgecolor='white',
                   linewidth=0.9, zorder=5)
        off_x = -70 if r > 0.7 else 8
        off_y = -14 if p > 0.28 else 10
        ax.annotate(lbl, (r, p), textcoords='offset points',
                    xytext=(off_x, off_y), fontsize=FS_ANNOT, color=col)

    ax.set_xlim(-0.02, 1.02)
    ax.set_ylim(0.0, 0.55)
    ax.set_xlabel('recall')
    ax.set_ylabel('precision')

    ax.legend(loc='center left', bbox_to_anchor=(1.02, 0.5),
              frameon=False)

    fig.tight_layout()
    _save(fig, 'fig6_pr_curve.pdf')


# --------------------------------------------------------------------------
# Fig 7: Review loop 2A vs 2B stacked bars
# v5: more bottom padding between the annotation text and the eps-axis label
# --------------------------------------------------------------------------

def fig7_review_loop():
    print("[fig7] review loop stacked comparison (v5: extra bottom padding)")

    total = 201

    a_cleared, a_confirmed, a_late_fp = 107, 85, 4
    a_pending = total - (a_cleared + a_confirmed + a_late_fp)

    b_cleared, b_confirmed, b_late_fp = 138, 57, 0
    b_pending = total - (b_cleared + b_confirmed + b_late_fp)

    labels = ['Context-free\nreviewer', 'Context-primed\nreviewer']
    cleared   = np.array([a_cleared,   b_cleared])
    confirmed = np.array([a_confirmed, b_confirmed])
    late_fp   = np.array([a_late_fp,   b_late_fp])
    pending   = np.array([a_pending,   b_pending])

    # v5: slightly taller figure to absorb the extra bottom padding
    fig, ax = plt.subplots(figsize=(W_DOUBLE, 3.9))
    y = np.arange(len(labels))
    h = 0.52

    col_clear = '#6BAB6E'
    col_conf  = '#F5A623'
    col_late  = '#8B0000'
    col_pend  = '#CCCCCC'

    left = np.zeros(len(labels))
    ax.barh(y, cleared,   h, left=left, color=col_clear, edgecolor='white',
            label='cleared by reviewer')
    left += cleared
    ax.barh(y, confirmed, h, left=left, color=col_conf,  edgecolor='white',
            label='confirmed failure')
    left += confirmed
    ax.barh(y, late_fp,   h, left=left, color=col_late,  edgecolor='white',
            label='late false positive')
    left += late_fp
    if pending.sum() > 0:
        ax.barh(y, pending, h, left=left, color=col_pend, edgecolor='white',
                label='other')

    for i in range(len(labels)):
        c = cleared[i]
        ax.text(c / 2.0, y[i], f'{c}  ({c/total*100:.1f}%)',
                va='center', ha='center', color='white',
                fontsize=FS_ANNOT, fontweight='bold')
        cf = confirmed[i]
        ax.text(c + cf / 2.0, y[i], f'{cf}  ({cf/total*100:.1f}%)',
                va='center', ha='center', color='#222',
                fontsize=FS_ANNOT, fontweight='bold')
        lf = late_fp[i]
        if lf > 0:
            ax.text(c + cf + lf / 2.0, y[i], f'{lf}',
                    va='center', ha='center', color='white',
                    fontsize=FS_ANNOT, fontweight='bold')

    ax.set_yticks(y)
    ax.set_yticklabels(labels, fontsize=FS_LABEL)
    ax.invert_yaxis()
    ax.set_xlim(0, total + 2)
    # v5: use labelpad to push the x-label down, away from any bottom text
    ax.set_xlabel(f'entries (n = {total})', fontsize=FS_LABEL, labelpad=10)

    ax.legend(loc='lower left', bbox_to_anchor=(0.0, 1.04),
              frameon=False, ncol=3, fontsize=FS_ANNOT)

    fig.tight_layout()
    # v5: reserve extra bottom margin so the axis label and any annotation
    # text below the plot have breathing room.
    fig.subplots_adjust(bottom=0.22)
    _save(fig, 'fig7_review_loop.pdf')


# --------------------------------------------------------------------------
# Fig 8: Scenario E collapse (gpt-4o-mini) - unchanged
# --------------------------------------------------------------------------

def fig8_scenario_e():
    print("[fig8] scenario E collapse (gpt-4o-mini)")

    names = ['register_user', 'login', 'verify_token', 'refresh_token',
             'request_password_reset', 'reset_password']
    combined = np.array([0.579, 0.820, 0.606, 0.414, 0.295, 0.394])
    per_fn   = np.array([0.627, 0.872, 0.911, 0.711, 0.788, 0.728])

    x = np.arange(len(names))
    w = 0.38

    fig, ax = plt.subplots(figsize=(W_DOUBLE, 3.6))

    ax.bar(x - w/2, combined, w, color=C_LOW,  edgecolor='white',
           label='combined prompt (1 call)')
    ax.bar(x + w/2, per_fn,   w, color=C_HIGH, edgecolor='white',
           label='per-function (6 calls)')

    ax.axhline(0.30, color=C_THRESH_SOFT, linestyle='--', linewidth=1.0, alpha=0.8)
    ax.text(len(names) - 0.5, 0.31, 'FLAGGED (0.30)', color=C_THRESH_SOFT,
            fontsize=FS_ANNOT, ha='right', va='bottom')

    for xi, v in zip(x - w/2, combined):
        ax.text(xi, v + 0.015, f'{v:.2f}', ha='center', va='bottom',
                fontsize=FS_ANNOT - 0.5, color='#333')
    for xi, v in zip(x + w/2, per_fn):
        ax.text(xi, v + 0.015, f'{v:.2f}', ha='center', va='bottom',
                fontsize=FS_ANNOT - 0.5, color='#333')

    ax.set_xticks(x)
    ax.set_xticklabels(names, rotation=22, ha='right')
    ax.set_ylim(0, 1.05)
    ax.set_ylabel(r'peak $\varepsilon$')
    ax.set_title('Scenario E: peak eps collapse under combined prompting (gpt-4o-mini)',
                 fontsize=FS_BASE)
    ax.legend(loc='upper right', frameon=False)

    _save(fig, 'fig8_scenario_e.pdf')


# --------------------------------------------------------------------------
# Fig comparison: Three-method comparison across four models
# v5: shared legend moved above the subplots, outside the data area
# --------------------------------------------------------------------------

def fig_comparison():
    print("[fig_comparison] three-method four-model comparison (v5: legend above plots)")

    models = ['GPT-4o', 'GPT-4o-mini', 'GPT-4-turbo', 'DeepSeek V3']

    eps_high   = [85, 70, 70, 85]
    pavg_high  = [85, 75, 90, 65]
    multi_high = [20, 10, 25, 35]

    eps_fp   = [50, 60, 60, 70]
    pavg_fp  = [50, 10, 40, 10]
    multi_fp = [10, 30, 30, 30]

    x = np.arange(len(models))
    w = 0.26

    # v5: slightly taller figure to leave room for legend above
    fig, axes = plt.subplots(1, 2, figsize=(W_DOUBLE, 3.9))

    ax = axes[0]
    b1 = ax.bar(x - w, eps_high,   w, color=C_LOW,   edgecolor='white',
                label=r'$\varepsilon$ (1$\times$ cost)')
    b2 = ax.bar(x,     pavg_high,  w, color=C_PAVG,  edgecolor='white',
                label=r'$p_{\mathrm{avg}}$ (1$\times$ cost)')
    b3 = ax.bar(x + w, multi_high, w, color=C_MULTI, edgecolor='white',
                label=r'multi-sample $N{=}5$ (5$\times$ cost)')

    for xi, v in zip(x - w, eps_high):
        ax.text(xi, v + 1.5, f'{v}', ha='center', va='bottom',
                fontsize=FS_ANNOT - 0.5, color='#333')
    for xi, v in zip(x, pavg_high):
        ax.text(xi, v + 1.5, f'{v}', ha='center', va='bottom',
                fontsize=FS_ANNOT - 0.5, color='#333')
    for xi, v in zip(x + w, multi_high):
        ax.text(xi, v + 1.5, f'{v}', ha='center', va='bottom',
                fontsize=FS_ANNOT - 0.5, color='#333')

    ax.set_xticks(x)
    ax.set_xticklabels(models, rotation=14, ha='right', fontsize=FS_TICK)
    ax.set_ylim(0, 100)
    ax.set_ylabel('HIGH detection rate (%)')
    ax.set_title('HIGH detection  (higher is better)', fontsize=FS_BASE)

    ax = axes[1]
    ax.bar(x - w, eps_fp,   w, color=C_LOW,   edgecolor='white')
    ax.bar(x,     pavg_fp,  w, color=C_PAVG,  edgecolor='white')
    ax.bar(x + w, multi_fp, w, color=C_MULTI, edgecolor='white')

    for xi, v in zip(x - w, eps_fp):
        ax.text(xi, v + 1.5, f'{v}', ha='center', va='bottom',
                fontsize=FS_ANNOT - 0.5, color='#333')
    for xi, v in zip(x, pavg_fp):
        ax.text(xi, v + 1.5, f'{v}', ha='center', va='bottom',
                fontsize=FS_ANNOT - 0.5, color='#333')
    for xi, v in zip(x + w, multi_fp):
        ax.text(xi, v + 1.5, f'{v}', ha='center', va='bottom',
                fontsize=FS_ANNOT - 0.5, color='#333')

    ax.set_xticks(x)
    ax.set_xticklabels(models, rotation=14, ha='right', fontsize=FS_TICK)
    ax.set_ylim(0, 100)
    ax.set_ylabel('LOW false-positive rate (%)')
    ax.set_title('LOW false-positive  (lower is better)', fontsize=FS_BASE)

    # v5: shared legend placed above both subplots, completely outside
    # the data area. bbox_to_anchor references the figure coordinate
    # system, so the legend never overlaps a bar.
    fig.legend(handles=[b1, b2, b3],
               loc='lower center',
               bbox_to_anchor=(0.5, 0.94),
               ncol=3,
               frameon=False,
               fontsize=FS_ANNOT)

    fig.tight_layout(rect=[0, 0, 1, 0.92])
    _save(fig, 'fig_comparison.pdf')


# --------------------------------------------------------------------------
# Fig intra_inter: Intra/inter distinction on Stripe Scenario A (unchanged)
# --------------------------------------------------------------------------

def fig_intra_inter():
    print("[fig_intra_inter] Stripe A: token distribution vs output diversity")

    fig, axes = plt.subplots(1, 2, figsize=(W_DOUBLE, 3.4))

    ax = axes[0]
    tokens  = ['Charge', 'PaymentIntent', 'other (top-3)',
               'other (top-4)', 'other (top-5)']
    probs   = [0.52, 0.47, 0.008, 0.001, 0.001]
    colors  = [C_HIGH, C_LOW, '#BBBBBB', '#BBBBBB', '#BBBBBB']

    y = np.arange(len(tokens))
    ax.barh(y, probs, color=colors, edgecolor='white', linewidth=0.8)
    for yi, p in zip(y, probs):
        if p >= 0.01:
            ax.text(p + 0.01, yi, f'{p:.2f}', va='center', ha='left',
                    fontsize=FS_ANNOT, color='#333')
        else:
            ax.text(p + 0.01, yi, f'{p:.3f}', va='center', ha='left',
                    fontsize=FS_ANNOT - 0.5, color='#999')

    ax.set_yticks(y)
    ax.set_yticklabels(tokens, fontsize=FS_TICK)
    ax.invert_yaxis()
    ax.set_xlim(0, 0.70)
    ax.set_xlabel('P(token)', fontsize=FS_LABEL)
    ax.set_title(r'Token distribution (generation time)'
                 '\n'
                 r'$\varepsilon = 0.878$  (FLAGGED)',
                 fontsize=FS_BASE - 0.5)

    ax.grid(axis='y', visible=False)

    ax = axes[1]

    sample_labels = ['sample 1', 'sample 2', 'sample 3',
                     'sample 4', 'sample 5']
    choices = ['Charge', 'Charge', 'Charge', 'Charge', 'Charge']

    y = np.arange(len(sample_labels))
    for yi, choice in zip(y, choices):
        ax.barh([yi], [1.0], color=C_HIGH, edgecolor='white', linewidth=0.8)
        ax.text(0.5, yi, choice, va='center', ha='center',
                fontsize=FS_LABEL, color='white', fontweight='bold')

    ax.set_yticks(y)
    ax.set_yticklabels(sample_labels, fontsize=FS_TICK)
    ax.invert_yaxis()
    ax.set_xticks([])
    ax.set_xlim(0, 1.0)
    ax.set_title(r'Output diversity ($N=5$, $T=0.7$)'
                 '\n'
                 r'diversity $= 0.00$',
                 fontsize=FS_BASE - 0.5)
    ax.grid(visible=False)

    fig.text(0.50, 0.10,
             r'The $52/47$ internal hesitation never surfaces as output variation.',
             ha='center', va='bottom', fontsize=FS_ANNOT, style='italic',
             color='#555')

    fig.tight_layout(rect=[0, 0.07, 1, 1])
    _save(fig, 'fig_intra_inter.pdf')


# --------------------------------------------------------------------------
# Fig token_focus (teaser): heat strip of per-token eps
# v5: legend moved off-axis, labels spread with leader lines, larger font
# --------------------------------------------------------------------------

def fig_token_focus():
    print("[fig_token_focus] teaser heat strip (v5: improved readability)")

    eps = _stripe_token_trajectory()
    n = len(eps)

    # v5: taller canvas so labels above the strip don't collide with
    # the title, and the colorbar below has room to breathe.
    fig, ax = plt.subplots(figsize=(W_DOUBLE, 2.6))

    cmap = plt.get_cmap('Reds')
    norm = plt.Normalize(vmin=0.0, vmax=1.0)

    # Draw the heat strip cells
    for i, e in enumerate(eps):
        ax.add_patch(plt.Rectangle((i, 0), 1, 1,
                                   facecolor=cmap(norm(e)),
                                   edgecolor='white', linewidth=0.3))

    # v5: mark all tokens above the flag threshold; spread their labels
    # horizontally above the strip with leader lines so none overlap.
    flagged = [(i, e) for i, e in enumerate(eps) if e >= 0.30]

    # Spread label x-positions evenly across the plot width to avoid
    # overlap. The original token position is preserved via a leader.
    if flagged:
        label_xs = np.linspace(3, n - 3, len(flagged))
    else:
        label_xs = []

    for (token_i, e), label_x in zip(flagged, label_xs):
        # Outline the flagged cell for visibility
        ax.add_patch(plt.Rectangle((token_i, 0), 1, 1,
                                   fill=False, edgecolor='black',
                                   linewidth=0.9))
        ax.annotate(fr'$\varepsilon={e:.2f}$',
                    xy=(token_i + 0.5, 1.0),
                    xytext=(label_x, 2.05),
                    fontsize=9,
                    ha='center', va='bottom', color='#222',
                    arrowprops=dict(arrowstyle='-', color='#666',
                                    linewidth=0.7,
                                    connectionstyle='arc3,rad=0'))

    ax.set_xlim(0, n)
    ax.set_ylim(-0.2, 2.6)
    ax.set_xticks([0, n // 4, n // 2, 3 * n // 4, n])
    ax.set_yticks([])
    ax.set_xlabel(f'token position (n = {n} retained semantic tokens)',
                  fontsize=FS_LABEL, labelpad=8)
    ax.set_title('Stripe Scenario A (GPT-4o): '
                 r'10 tokens exceed $\varepsilon\geq 0.30$',
                 fontsize=FS_BASE - 0.5, pad=10)
    ax.grid(visible=False)
    for spine in ('top', 'right', 'left'):
        ax.spines[spine].set_visible(False)

    # v5: colorbar anchored clearly below the strip so its tick labels do
    # not collide with the x-axis label.
    sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=ax, orientation='horizontal',
                        fraction=0.05, pad=0.45, aspect=40)
    cbar.set_label(r'per-token $\varepsilon$', fontsize=FS_ANNOT)
    cbar.ax.tick_params(labelsize=FS_ANNOT - 1)

    fig.tight_layout()
    _save(fig, 'fig_token_focus.pdf')


# --------------------------------------------------------------------------
# Fig token_focus_detail: per-token eps trajectory with thresholds (unchanged)
# --------------------------------------------------------------------------

def fig_token_focus_detail():
    print("[fig_token_focus_detail] per-token trajectory")

    eps = _stripe_token_trajectory()
    n = len(eps)
    x = np.arange(n)

    fig, ax = plt.subplots(figsize=(W_DOUBLE, 3.2))

    # Two colours: flagged (>= 0.30) vs confident background.
    # Paused tier (>= 0.95) is shown separately for the peak bar only.
    colors = ['#D65F5F' if e >= 0.95
              else '#F5A623' if e >= 0.30
              else '#BBBBBB'
              for e in eps]
    ax.bar(x, eps, color=colors, edgecolor='none', width=0.9)

    # Only the flag threshold line — 0.65 no longer exists as a tier boundary.
    ax.axhline(0.30, color=C_THRESH_SOFT, linestyle='--', linewidth=1.0,
               label=r'flag threshold ($\varepsilon = 0.30$)')

    # Annotate the two most uncertain tokens (the method-selector decision).
    # Trigger at 0.70 (the accumulation floor) — no tier label attached.
    annotated = [(i, e) for i, e in enumerate(eps) if e >= 0.70]
    for i, e in annotated:
        label = ('.Charge / .PaymentIntent' if i == 22
                 else 'adjacent selector')
        # Place labels to the right and above, away from the upper-left legend.
        ax.annotate(f'{label}\nε={e:.3f}',
                    xy=(i + 0.5, e),
                    xytext=(min(i + 12, n - 14), e + 0.10),
                    fontsize=FS_ANNOT - 0.5,
                    ha='left', va='bottom', color='#222',
                    arrowprops=dict(arrowstyle='->', color='#444',
                                    linewidth=0.7))

    ax.set_xlim(-1, n)
    ax.set_ylim(0, 1.15)
    ax.set_xlabel(f'token position (of {n} retained semantic tokens)',
                  fontsize=FS_LABEL)
    ax.set_ylabel(r'$\varepsilon_t$', fontsize=FS_LABEL)

    summary = (f'total retained tokens: {n}\n'
               f'above flag (0.30): 10  ({10/n*100:.1f}%)\n'
               f'above 0.70: 2  ({2/n*100:.1f}%)')
    ax.text(0.02, 0.98, summary,
            transform=ax.transAxes, fontsize=FS_ANNOT - 0.5,
            va='top', ha='left',
            bbox=dict(facecolor='white', edgecolor='#AAA', linewidth=0.5))

    # Legend placed bottom-right, well clear of the annotations above.
    ax.legend(loc='lower right', frameon=False, fontsize=FS_ANNOT)

    fig.tight_layout()
    _save(fig, 'fig_token_focus_detail.pdf')


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

# v5 flag: set True to also regenerate the PR curve figure (removed from
# the paper in v5 but kept here for reproducibility).
REGENERATE_PR_CURVE = False


def main():
    print(f"output dir: {FIG_DIR}")

    # Unchanged from v4
    fig3_scenarios()
    fig7_review_loop()
    fig8_scenario_e()
    fig_comparison()
    fig_intra_inter()

    # Updated in v5
    fig_token_focus()
    fig_token_focus_detail()

    # v5: no longer regenerated by default
    if REGENERATE_PR_CURVE:
        fig6_pr_curve()

    print("done.")


if __name__ == '__main__':
    main()
